apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: chefkoch-demo-v1
    labels:
      name: chefkoch-demo-v1
      project: k8-rolling-demo
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: demo
          component: web
          name: chefkoch-demo
          release: v1
      spec:
        containers:
          - name: chefkoch-demo
            image: "b00gizm/chefkoch-demo:1"
            imagePullPolicy: IfNotPresent
            ports:
              - {containerPort: 80}
            readinessProbe:
              tcpSocket:
                port: 80

- apiVersion: v1
  kind: Service
  metadata:
    name: chefkoch-demo-np
    labels:
      name: chefkoch-demo-np
      project: k8-rolling-demo
  spec:
    type: NodePort
    ports:
    - port: 80
      nodePort: 80
      protocol: TCP
    selector:
      app: demo
      component: web
